# roles/RPi-Monitor/tasks/main.yml

### RPi-Monitor ###
---

# CHECK IF RPi-Monitor ALREADY EXISTS
- name: check if RPi-Monitor exists already
  ansible.builtin.stat:
    path: /etc/rpimonitor/
  become: true
  register: stat_result

  # APT INSTALL dirmngr FOR RPi-Monitor
- name: apt install dirmngr for RPi-Monitor
  ansible.builtin.apt:
    update-cache: true
    pkg: dirmngr
    state: present
  become: true
  when: stat_result.stat.exists

  # INSTALL RPI-MONITOR‘S PUBLIC KEY
# - name: Install RPi-Monitor‘s public key
#   command: apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2C0D3C0F
#   become: true

  # INSTALL RPI-MONITOR‘S PUBLIC KEY
- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2C0D3C0F

  # ADD RPI-MONITOR INTO LIST OF REPOSITORY
- name: Add RPi-Monitor into list of repository
  ansible.builtin.get_url:
    url: http://goo.gl/vewCLL
    dest: /etc/apt/sources.list.d/rpimonitor.list
    mode: 644
  when: stat_result.stat.exists

  # APT INSTALL RPi-Monitor
- name: apt install RPi-Monitor
  ansible.builtin.apt:
    update-cache: true
    pkg: rpimonitor
  become: true
  when: stat_result.stat.exists

  # RPI-MONITOR UPDATE PACKAGES INFORMATION
- name: RPi-Monitor update packages information
  ansible.builtin.command: /etc/init.d/rpimonitor update
  become: true
  when: stat_result.stat.exists
