# roles/RPi-Monitor/tasks/main.yml

### RPi-Monitor ###
---
- name: check if RPi-Monitor exists already
  ansible.builtin.stat:
    path: /etc/rpimonitor/
  become: true
  register: stat_result

- name: apt install dirmngr for RPi-Monitor
  ansible.builtin.apt:
    update-cache: true
    pkg: dirmngr
    state: present
  become: true
  when: not stat_result.stat.exists

# - name: Install RPi-Monitor‘s public key
#   command: apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 2C0D3C0F
#   become: true

- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2C0D3C0F

- name: Add RPi-Monitor into list of repository
  ansible.builtin.get_url:
    url: http://goo.gl/vewCLL
    dest: /etc/apt/sources.list.d/rpimonitor.list
    mode: 644
  when: not stat_result.stat.exists

- name: apt install RPi-Monitor
  ansible.builtin.apt:
    update-cache: true
    pkg: rpimonitor
  become: true
  when: not stat_result.stat.exists

- name: RPi-Monitor update packages information
  ansible.builtin.command: /etc/init.d/rpimonitor update
  become: true
  when: not stat_result.stat.exists
