# roles/git_keys/tasks/main.yaml

### GIT ###
---
- name: Populate installed packages
  ansible.builtin.package_facts:
    manager: "auto"

- name: Check ssh key exists on remote
  ansible.builtin.stat:
    path: /home/pi/.ssh/id_rsa
  register: ssk_key

- name: Generate ssh key
  community.crypto.openssh_keypair:
    path: /home/pi/.ssh/id_rsa
    owner: '{{ user }}'
    group: '{{ user }}'
  when: not ssk_key.stat.exists

- name: Read SSH public key to authorize
  ansible.builtin.command: cat /home/pi/.ssh/id_rsa.pub
  register: ssh_pub_key
  check_mode: false
  when: not ssh_pub_key.stdout

- name: Ensure git is present
  ansible.builtin.apt:
    name: git
    state: present
  become: true

- name: Add key to GitHub
  delegate_to: localhost
  ansible.builtin.command:
    module: github_key
    name: 'pi-{{ ansible_hostname }}'
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'
  become: true
  # TODO is an issue as not always this user so hop to determine the user when using become true form the off
  become_user: 'gary' # '{{ username }}'

- name: Set git config email
  community.general.git_config:
    name: user.email
    scope: global
    value: '{{ git_user_email }}'
  become: true
  become_user: '{{ user }}'

- name: Set git config username
  community.general.git_config:
    name: user.name
    scope: global
    value: '{{ git_user_name }}'
  become: true
  become_user: '{{ user }}'
