# roles/git_keys/tasks/main.yaml

### GIT ###
---
- name: Populate installed packages
  ansible.builtin.package_facts:
    manager: "auto"

- name: Check ssh key exists on remote
  ansible.builtin.stat:
    path: /home/pi/.ssh/id_rsa
  register: ssk_key

- name: Generate ssh key
  community.crypto.openssh_keypair:
    path: /home/pi/.ssh/id_rsa
    owner: '{{ user }}'
    group: '{{ user }}'
  when: not ssk_key.stat.exists

- name: Read SSH public key file
  ansible.builtin.slurp:
    src: /home/pi/.ssh/id_rsa.pub
  register: ssh_pub_key_content

- name: Add key to GitHub
  community.general.github_key:
    name: 'pi-{{ ansible_hostname }}'
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key_content.content | b64decode }}'

- name: Ensure git is present
  become: true
  ansible.builtin.apt:
    name: git
    state: present

- name: Set git config email
  become: true
  become_user: '{{ user }}'
  community.general.git_config:
    name: user.email
    scope: global
    value: '{{ git_user_email }}'

- name: Set git config username
  become: true
  become_user: '{{ user }}'
  community.general.git_config:
    name: user.name
    scope: global
    value: '{{ git_user_name }}'
