# Raspberry Pi device setup - Gary Mc Dermott 2019 - 2023
---

- name: Setup
  hosts: nodes
  become: true
  vars_files:
    - vars.yaml
  vars:
    user: pi

  roles:
#    - { role: keyless }
#    - { role: bootstrap }
#    - { role: customization }
#    - { role: docker, when: model_four == 'true'}
#    - { role: fail2ban }
#    - { role: git_keys }
#    - { role: monitoring }
#    - { role: docker, when: model_four == 'true' }
    - { role: mount, when: model_four == 'true' }
#    - { role: services } # TODO fix services and verify working
