#Home Monitoring Project - Device setup - Gary Mc Dermott 2019
---

- name: Basic Setup
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  # If off some steps will fail as ansible facts not set
  #gather_facts: false

  roles:
     - { role: keyless }
#     - { role: fail2ban }
#     - { role: bootstrap }
#     - { role: customization }
#     - { role: docker }
#     - { role: git}
# TODO remove tailscale??
# TODO fail2ban setup
# TODO review below, refactor as monitoring needed others seperate playbook
#     - { role: tailscale }
#     - { role: monitoring }
##     - { role: datadog.datadog, become: yes }
#      - { role: monitoring , when: model_four }
#     - { role: RPi-Monitor }
#     - { role: sensor , tags: [ "sensor" ] }
#     - { role: sensor }
#     - { role: docker , when: model_four }
#     - { role: database , when: model_three }
