Vagrant.configure("2") do |config|
  config.vm.box = "PersistentCoder/raspberry-pi-desktop-32bit"
  config.vm.box_version = "1.0.0"
  config.vm.provider "virtualbox" do |vb|
    vb.gui    = false
    vb.memory = "2048"
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook            = "playbook.yaml"
    ansible.vault_password_file = "../.vault_pass"
    ansible.verbose             = ""
  end
end
