# roles/database/tasks/main.yaml

### SETUP DATABASE ###
---
- name: APT-get update
  ansible.builtin.apt:
    update-cache: true
  become: true

- name: Install MySQL & python-mysqldb
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  with_items:
    - python-mysqldb
    - mysql-server
  become: true

## TODO review this and see if can knock a template file together
# - name: copy cnf
#   copy: src=.my.cnf dest=~/.my.cnf owner=ubuntu mode=0644
#   become: true

- name: Start the MySQL service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  become: true

- name: Update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  become: true
