# roles/database/tasks/main.yml

### SETUP DATABASE ###
---
- name: apt-get update
  apt:
    update-cache: true
  become: true

- name: Install MySQL & python-mysqldb
  become: true
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - python-mysqldb
    - mysql-server
    # TODO review this and see if can knock a template file together
    #- name: copy cnf
    #  copy: src=.my.cnf dest=~/.my.cnf owner=ubuntu mode=0644
    #  become: true

- name: Start the MySQL service
  become: true
  service:
    name: mysql
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  become: true
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
