# roles/monitoring/tasks/main.yaml

### MONITORING ###
---
- name: Populate installed packages
  package_facts:
    manager: "auto"

- name: Check if datadog config file exists
  ansible.builtin.stat:
    path: /etc/datadog-agent/datadog.yaml
  register: ddog_config_file

- name: Install Datadog iot agent 7
  ansible.builtin.apt:
    deb: "{{ datadog_url }}"
    # saved the deb file to S3 but still pulling from ddog. check terraform state bucket
    # if ever this stops working as know this version does the business. But does it? - Feb2023
  when: '"datadog-agent" not in ansible_facts.packages'

- name: Add datadog config
  ansible.builtin.template:
    src: datadog.yaml.js
    dest: /etc/datadog-agent/datadog.yaml
    owner: dd-agent
    group: dd-agent
    mode: '644'
  when: not ddog_config_file.stat.exists

- name: Enable datadog service
  ansible.builtin.service:
    name: datadog-agent
    enabled: true
    state: started
  when: '"datadog-agent" not in ansible_facts.packages'
