# roles/customization/tasks/main.yaml

### CUSTOMIZATION ###
---
- name: Populate installed packages
  ansible.builtin.package_facts:
    manager: "auto"

- name: Populate service facts
  ansible.builtin.service_facts:
  register: services_state

- name: Install common software
  become: true
  ansible.builtin.package:
    update-cache: true
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - zsh
    - mc
    - ncdu
    - tree
    - vim
    # For monitoring
    - apt-transport-https
    - curl
    - gnupg
  when: ('"git" not in ansible_facts.packages') or
        ('"zsh" not in ansible_facts.packages') or
        ('"mc" not in ansible_facts.packages') or
        ('"ncdu" not in ansible_facts.packages') or
        ('"tree" not in ansible_facts.packages') or
        ('"vim" not in ansible_facts.packages') or
        ('"apt-transport-https" not in ansible_facts.packages') or
        ('"curl" not in ansible_facts.packages') or
        ('"gnupg" not in ansible_facts.packages') or

# Issue with newer Ras Pi OS version not having htis set so need to manually do it for k3s to work
- name: Add cgroup_memory to /boot/cmdline.txt for k3s
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
    regexp: '^(console=serial0,115200 console=tty1 root=PARTUUID=[a-f0-9]+-02 rootfstype=ext4 fsck\.repair=yes rootwait)(.*)$'
  notify:
    - Restart

- name: Create config/mc directory if it does not exist
  ansible.builtin.file:
    path: /home/pi/.config/mc/
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0700'

- name: Golden Midnight Commander panels
  ansible.builtin.template:
    src: panels.ini
    dest: /home/pi/.config/mc/panels.ini
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'

- name: Golden Midnight Commander ini file
  ansible.builtin.template:
    src: ini
    dest: /home/pi/.config/mc/ini
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'

- name: Creates repos directory
  ansible.builtin.file:
    path: /home/pi/repos
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0755'

- name: Check if oh-my-zsh exists
  ansible.builtin.stat:
    path: '/home/{{ user }}/.oh-my-zsh'
  register: ohmyzsh_result

- name: Git clone oh my zsh
  ansible.builtin.git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: '/home/{{ user }}/.oh-my-zsh'
    version: master
  become: true
  become_user: '{{ user }}'
  when: not ohmyzsh_result.stat.exists

- name: Set permissions of oh-my-zsh for users
  ansible.builtin.file:
    path: '/home/{{ user }}/.oh-my-zsh'
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability).
    mode: 'go-w'
    recurse: true

- name: Golden .zshrc
  ansible.builtin.template:
    src: .zshrc
    dest: '/home/{{ user }}/.zshrc'
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0644'

- name: Golden theme for oh my zsh - racotencnic
  become: true
  ansible.builtin.template:
    src: racotecnic.zsh-theme
    dest: '/home/{{ user }}/.oh-my-zsh/themes/racotecnic.zsh-theme'
    owner: '{{ user }}'
    mode: '0644'

- name: 'Set zsh default shell for user: {{ user }}'
  ansible.builtin.user:
    name: '{{ user }}'
    shell: /bin/zsh

- name: Restart SSH service
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Disable Password Authentication
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: true
  notify:
    - Restart
