# roles/tailscale/tasks/main.yml

### TAILSCALE ###
---
  # ADD TAILSCALE APT KEY
- name: Add tailscale Apt signing key
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/unstable/ubuntu/bionic.gpg
    state: present

  # ADD SOURCES FILE
- name: Add specified repository into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/raspbian buster main
    state: present
    filename: tailscale

  # APT INSTALL TAILSCALE
- name: install Tailscale
  become: yes
  package:
    update-cache: true
    name: '{{ item }}'
    state: present
  with_items:
    - tailscale

- name: Start Tailscale
  # This needs to be updated as expires after 90 days
  # login to tailscale nad generate new one not ususal addr
  command: tailscale up --authkey {{ tailscale_api }}
  become: true
