# roles/fail2ban/tasks/main.yaml

### Fail2Ban ###
---
- name: Populate installed packages
  ansible.builtin.package_facts:
    manager: "auto"

- name: Install fail2ban apt package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - fail2ban
  when: '"fail2ban" not in ansible_facts.packages'

- name: Check if fail2ban config already in place
  ansible.builtin.stat:
    path: /etc/fail2ban/jail.local
  register: fail2ban_config

- name: Override the basic fail2ban configuration with .local file
  ansible.builtin.copy:
    src: fail2ban.config
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  when: not fail2ban_config.stat.exists
