# roles/fail2ban/tasks/main.yml

### Fail2Ban ###
---
  - name: Install fail2ban package apt
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      cache_valid_time: 3600
    with_items:
      - fail2ban

  - name: Check if fail2ban config already in place
    stat:
      path: /etc/fail2ban/jail.local
    register: fail2ban_config

  - name: override the basic fail2ban configuration with .local file
    copy:
      src: '../../../templates/fail2ban.config'
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: 0644
    when: fail2ban_config == false
