# roles/hostname/tasks/main.yml

### KEYLESS ACCESS ###
---

  # CREATE .ssh DIRECTORY
- name: Creates SSH directory
  file:
    path: /home/pi/.ssh
    state: directory
    owner: pi
    group: pi
    mode: 0700

  # Personal laptop key
- name: Set authorized key taken from id rsa pub
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  # Android key
- name: Set authorized key taken from id rsa pub
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', '../../../templates/android.pub') }}"