# roles/hostname/tasks/main.yaml

### KEYLESS ACCESS ###
---
- name: Creates .ssh directory
  ansible.builtin.file:
    path: /home/pi/.ssh
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0700

- name: Set authorized key Linux personal
  authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: "user == 'pi'"

- name: Set authorized key Windows
  authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ lookup('file', '../../../templates/win.pub') }}"

- name: Set authorized key Android device connectbot
  authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ lookup('file', '../../../templates/android.pub') }}"
