# roles/hostname/tasks/main.yml

### KEYLESS ACCESS ###
---
# CREATE .ssh DIRECTORY
- name: Creates SSH directory
  ansible.builtin.file:
    path: /home/pi/.ssh
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0700
  when: "user == 'pi'"

# Personal laptop key
- name: Set authorized key taken from id rsa pub
  authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# Windows key
- name: Set windows authorized key
  authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ lookup('file', '../../../templates/win.pub') }}"

# Android key
- name: Set authorized key taken from connectbot on android device
  authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ lookup('file', '../../../templates/android.pub') }}"
