# roles/hostname/tasks/main.yaml

### KEYLESS ACCESS ###
---
- name: Check if /home/pi/.ssh directory exists
  ansible.builtin.stat:
    path: /home/pi/.ssh
  register: ssh_dir

- name: Creates .ssh directory
  ansible.builtin.file:
    path: /home/pi/.ssh
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: '0700'
  when: not ssh_dir.stat.exists

- name: Set authorized key Linux personal
  ansible.posix.authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: "user == 'pi'"

- name: Set authorized key Windows
  ansible.posix.authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ lookup('file', '../../../templates/win.pub') }}"

- name: Set authorized key Android device connectbot
  ansible.posix.authorized_key:
    user: '{{ user }}'
    state: present
    key: "{{ lookup('file', '../../../templates/android.pub') }}"
