# roles/docker/tasks/main.yml

### DOCKER ###
---
- name: Check if Docker is installed
  stat:
    path: /usr/bin/docker
  register: statdocker_result

- name: Update apt and install docker.io
  apt:
    update_cache: yes
    name: docker.io
    state: latest
  when: statdocker_result.stat.exists == False

- name: Give the pi user the ability to run Docker
  user:
    name: pi
    groups: docker
    append: yes
  when: statdocker_result.stat.exists == False

- name: Reboot to initiate permissions for pi
  reboot:
    pre_reboot_delay: 3
    msg: "Reboot - initiated by Ansible"
    test_command: uptime
  when: statdocker_result.stat.exists == False
