# roles/docker/tasks/main.yaml

### DOCKER ###
---
- name: Populate installed packages
  ansible.builtin.package_facts:
    manager: "auto"

- name: Install docker.io & docker-compose
  ansible.builtin.apt:
    update_cache: true
    name: '{{ item }}'
    state: present
  with_items:
    - docker.io
    - docker-compose
  when: ('"docker.io" not in ansible_facts.packages')
  when: |
         ('"docker.io" not in ansible_facts.packages') or
         ('"docker-compose" not in ansible_facts.packages')

- name: Give the pi user the ability to run Docker
  ansible.builtin.user:
    name: pi
    groups: docker
    append: true
  when: '"docker.io" not in ansible_facts.packages'
  notify:
    - Restart
