# roles/docker/tasks/main.yaml

### DOCKER ###
---
- name: Check if Docker is installed
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_result

- name: Update apt and install docker.io
  ansible.builtin.apt:
    update_cache: true
    name: docker.io
    state: present
  when: not docker_result.stat.exists

- name: Give the pi user the ability to run Docker
  ansible.builtin.user:
    name: pi
    groups: docker
    append: true
  when: not docker_result.stat.exists
#  notify:
#    - Restart system
