# roles/docker/tasks/main.yaml

### DOCKER ###
---
- name: Populate installed packages
  ansible.builtin.package_facts:
    manager: "auto"

- name: Update apt and install docker.io
  ansible.builtin.apt:
    update_cache: true
    name: docker.io
    state: present
  when: '"docker.io" not in ansible_facts.packages'

- name: Give the pi user the ability to run Docker
  ansible.builtin.user:
    name: pi
    groups: docker
    append: true
  when: '"docker.io" not in ansible_facts.packages'
  notify:
    - Restart
