name: Test playbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
  workflow_dispatch:


jobs:
  vagrant_test:
    name: Test playbook on Vagrant box
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v4

      - name: Cache ansible
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/ansible
          key: ${{ runner.os }}-ansible
          restore-keys: |
            ${{ runner.os }}-ansible

      - name: Setup Ansible via brew
        uses: lyricwulf/abc@v1
        with:
          macos: ansible

      - name: Setup ansible vault password
        run: printf ${{ secrets.VAULT_PASS }} > .vault_pass

      - name: Setup pub key for keyless role
        run: printf ${{ secrets.PUB_KEY }} > ~/.ssh/id_rsa.pub

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant
          restore-keys: |
            ${{ runner.os }}-vagrant

      - name: Run vagrant up
        run: vagrant up --provision
        working-directory: ./tests
